### ISSUE TITLE
Práctica2

### ISSUE THREAD

**Issue by BautistaLizbeth** [SistemasTecTlaxiaco/compuertas-logicas-equipo-f4#1]
[Practica2_MD[1].pdf](https://github.com/user-attachments/files/18050314/Practica2_MD.1.pdf)

**Comment by Proyect-A16** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:22/25
Total:97/100

**Comment by josealfredo79** [comment]
bien hecho y revisado...
