### ISSUE TITLE
practica 2

### ISSUE THREAD

**Issue by AlynGomez12** [SistemasTecTlaxiaco/compuertas-logicas-equipo-f4#2]
[Practica 2 mate (1) (7).pdf](https://github.com/user-attachments/files/18065734/Practica.2.mate.1.7.pdf)

**Comment by Proyect-A16** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
